apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-{{ .Release.Name }}-frontend
  labels:
    app: {{ .Values.env }}-{{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.env }}-{{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-{{ .Release.Name }}-frontend
    spec:
      nodeSelector:
        karpenter.sh/nodepool: default
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.frontTag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: app.{{ .Values.env }}.{{ .Values.domain_name }}

