frontend:
  image:
    repository: yulianbortsov/3tier-front
    frontTag: 543bd2a2baa053c1bb574b6a78acdb5366e21c72
backend:
  image:
    repository: yulianbortsov/3tier-back
    backTag: 2555b2be2752467b296953748b0c25b7511b3a79

env: production
