apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Release.Name }}-backend
  labels:
    app: {{ .Values.env }}-{{ .Release.Name }}-backend
spec:
  {{- with .Values.backend.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port}}
  {{- end }}
  selector:
    app: {{ .Values.env }}-{{ .Release.Name }}-backend