apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.env }}-{{ .Release.Name }}-backend-monitor
  labels:
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: {{ .Values.env }}-{{ .Release.Name }}-backend
  endpoints:
    - targetPort: 5000
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
      