# Default values for 3tier-app.

env: dev
frontend:
  image:
    repository: nginx
    frontTag: alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: True
    host: app.ybort.shop




backend:
  image:
    repository: yulianbortsov/3tier-back
    backTag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 5000
  livenessProbe:
    httpGet:
      path: /api
      port: 5000
    initialDelaySeconds: 7
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /api
      port: 5000
    initialDelaySeconds: 7
    periodSeconds: 10

rds:
  remoteRefKey: dev-DevOpsProject/rds-credentials
  secretName: rds-credentials
  secretKeys:
    host: host
    port: port
    dbname: dbname
    username: username
    password: password

global:
  defaultStorageClass: gp2  

postgresql:
  auth:
    username: user
    database: app_db
    existingSecret: postgres-pass
    secretKeys:
      userPasswordKey: db-pass
      adminPasswordKey: db-admin-pass
  primary:
    persistence:
      enabled: true
      size: 1Gi

secretStore:
  remoteRefKey: 3tier/postgresql
  remoteRefProperty: 3tier-app-postgres-pass
  remoteRefPropertyAdmin: 3tier-app-postgres-admin-pass
  region: us-east-1  
