# Default values for 3tier-app.

env: dev
frontend:
  image:
    repository: nginx
    frontTag: alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: True
    host: app.dev.ybort.shop




backend:
  image:
    repository: yulianbortsov/3tier-back
    backTag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 5000
  livenessProbe:
    httpGet:
      path: /api
      port: 5000
    initialDelaySeconds: 7
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /api
      port: 5000
    initialDelaySeconds: 7
    periodSeconds: 10

rds:
  remoteRefKey: dev-DevOpsProject/rds-cred
  secretName: rds-credtials
  secretKeys:
    host: host
    port: port
    dbname: dbname
    username: username
    password: password

global:
  defaultStorageClass: gp2  

