frontend:
  image:
    repository: yulianbortsov/3tier-front
    frontTag: 60e77d2c8ff3299930a7cddb59eed912ebd9b3e0
backend:
  image:
    repository: yulianbortsov/3tier-back
    backTag: 2555b2be2752467b296953748b0c25b7511b3a79

env: dev
