frontend:
  image:
    repository: yulianbortsov/3tier-front
    frontTag: 2ba4782d4a8edcdb65f1461144d35f3dcc95517a
backend:
  image:
    repository: yulianbortsov/3tier-back
    backTag: 451f1a81a1b0f7c8b8a913776d9603e6bf702aef

env: dev
