frontend:
  image:
    repository: yulianbortsov/3tier-front
    frontTag: 19e6c6b0649e9e0574d55a3e69c42c4bb008a5bf
backend:
  image:
    repository: yulianbortsov/3tier-back
    backTag: 2555b2be2752467b296953748b0c25b7511b3a79

env: dev
