apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
spec:
  secretStoreRef:
    name: {{ .Release.Name }}-secretstore
    kind: ClusterSecretStore
  target:
  {{- with .Values.rds }}
    name: {{ .secretName }}
  data:
    - secretKey: {{ .secretKeys.host }}
      remoteRef: 
        key: {{ .remoteRefKey }} 
        property: {{ .secretKeys.host }}
    - secretKey: {{ .secretKeys.port }}
      remoteRef:
        key: {{ .remoteRefKey }}
        property: {{ .secretKeys.port }}
    - secretKey: {{ .secretKeys.dbname }}
      remoteRef:
        key: {{ .remoteRefKey }}
        property: {{ .secretKeys.dbname }}
    - secretKey: {{ .secretKeys.username }}
      remoteRef:
        key: {{ .remoteRefKey }}
        property: {{ .secretKeys.username }}
    - secretKey: {{ .secretKeys.password }}
      remoteRef:
        key: {{ .remoteRefKey }}
        property: {{ .secretKeys.password }}