apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-secretstore
spec:
  provider:
      aws:
        service: SecretsManager
        {{- with .Values.secretStore }}
        region: {{ .region }}
        auth:
          jwt:
            serviceAccountRef:
              name: external-secrets-sa
              namespace: external-secrets
        {{- end }}