name: Build new backend image and Deploy

on:
  push:
    branches:
      - dev
      - staging
      - production
    paths:
      - 'app-repo/code/app.py'

  workflow_run:
    workflows: ["Build new frontend image and Deploy"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # - name: Build and Push
        #   uses: docker/build-and-push-action@v5
        #   with:
        #     context: ./app-repo/code
        #     file: ./app-repo/code/Dockerfile
        #     push: true
        #     tags: |
        #       ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ github.sha }}
        #       ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ steps.branch-name.outputs.BRANCH_NAME }}-latest
        #     cache-from: type=gha
        #     cache-to: type=gha, mode=max
      - name: Build and Tag
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ github.sha }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ steps.branch-name.outputs.BRANCH_NAME }}-latest \
          -f ./app-repo/code/Dockerfile ./app-repo/code
      - name: Push Image
        run: |
          for i in 1 2 3; do
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ github.sha }} && break || sleep 10;
          done
          for i in 1 2 3; do
            docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ steps.branch-name.outputs.BRANCH_NAME }}-latest && break || sleep 10;
          done
      - name: Change values file in gitops repo
        run: |
          sed -i "s/backTag: .*/backTag: ${{ github.sha }}/" ./gitops-repo/environments/${{ steps.branch-name.outputs.BRANCH_NAME }}/values.yaml
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ./gitops-repo/environments/${{ steps.branch-name.outputs.BRANCH_NAME }}/values.yaml
          git commit -m "Update backend image tag to ${{ github.sha }} for ${{ steps.branch-name.outputs.BRANCH_NAME }} environment"
          git push