name: Build new backend image and Deploy

on:
  push:
    paths:
      - 'app-repo/code/app.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Tag
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ github.sha }} -f ./app-repo/code/Dockerfile ./app-repo/code
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.BACKEND_IMAGE }}:${{ github.sha }}
      - name: Change values file in gitops repo
        run: |
          sed -i "s/tag: .*/tag: ${{ github.sha }}/" ./gitops-repo/environments/dev/values.yaml
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ./gitops-repo/environments/dev/values.yaml
          git commit -m "Update backend image tag to ${{ github.sha }}"
          git push